     1	plugins { id 'com.android.application' }
     2	
     3	android {
     4	    namespace 'com.metisai.mobile'
     5	    compileSdk 35
     6	    defaultConfig {
     7	        applicationId 'com.metisai.mobile'
     8	        minSdk 23
     9	        targetSdk 35
    10	        versionCode 1
    11	        versionName '1.0.0'
    12	    }
    13	}
    14	
    15	dependencies {
    16	    implementation 'io.noties.markwon:core:4.6.2'
    17	    implementation 'io.noties.markwon:ext-tables:4.6.2'
    18	    implementation 'io.noties.markwon:ext-strikethrough:4.6.2'
    19	}
